"""
Author: Michael Yoo Fatemi
Date: April 25, 2024
"""

import traceback
from typing import Union, Tuple, Literal

class StatefulLanguageModelProgramExecutor:

    def __init__(self, vars = None):
        self.vars_ptr = {'vars': {**(vars or {})}}

    def update(self, **vars):
        self.vars_ptr['vars'].update(vars)

    def check(self, source: str):
        # same checks as those made by voxposer
        source.replace("import numpy as np", "")

        if 'import' in source:
            return (False, "Cannot import any libraries beyond numpy")
        if '__' in source:
            return (False, "Cannot use any special variables")
        return (True, None)
    
    def execute(self, source: str) -> Union[Tuple[Literal[True], None], Tuple[Literal[False], str]]:
        ok, msg = self.check(source)
        if not ok:
            return (False, msg)

        globals_ = {'exec': None, 'eval': None, 'open': None}
        locals_ = {**self.vars_ptr['vars'], "__vars_ptr": self.vars_ptr}

        # capture changes made
        source += """
### AUTOGENERATED CODE TO CAPTURE LOCAL VARIABLES ###
__vars_ptr['vars'] = {k: v for (k, v) in locals().items() if '__' not in k}
"""
        try:
            exec(source, globals_, locals_)
            
            return (True, None)
        except Exception as e:
            error_str = traceback.format_exc()
            print(error_str)
            print(e)

            return (False, error_str)

def test():
    executor = StatefulLanguageModelProgramExecutor()

    res = executor.execute("a = 5")
    res = executor.execute("print(a)")
    res = executor.execute("v = []\nfor x in range(5):\n\tv.append(x)")
    res = executor.execute("print(v)")

if __name__ == '__main__':
    test()
